module.exports = {
  content: ['./public/stitch/categories.html', './public/stitch/category-products.html'],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        'on-surface-variant': '#718096',
        'surface-dim': '#C8E9FF',
        'secondary-container': '#ffc4b3',
        'on-tertiary-container': '#583700',
        'on-tertiary-fixed': '#3d2500',
        'outline-variant': '#C6DFF2',
        'surface-container': '#E0F2FF',
        'primary-fixed-dim': '#87CEEB',
        surface: '#F0F8FF',
        'secondary-fixed-dim': '#ffb199',
        'tertiary-fixed-dim': '#eea840',
        'on-primary-fixed': '#103A63',
        'on-primary-fixed-variant': '#1E4E7F',
        'tertiary-fixed': '#feb64c',
        'tertiary-container': '#feb64c',
        outline: '#9EC7E8',
        'surface-container-lowest': '#ffffff',
        'primary-container': '#87CEEB',
        'on-tertiary-fixed-variant': '#644000',
        'inverse-on-surface': '#8AA9C7',
        'on-primary-container': '#1F4D7E',
        'secondary-fixed': '#ffc4b3',
        'on-surface': '#1A365D',
        'surface-container-low': '#EAF5FF',
        error: '#b02500',
        'on-secondary-fixed-variant': '#8d3416',
        'on-primary': '#E0F2FF',
        'secondary-dim': '#8b3315',
        'surface-container-high': '#D9EEFF',
        tertiary: '#7f5200',
        'primary-dim': '#2B6CB0',
        secondary: '#9b3e20',
        'on-error': '#ffefec',
        'on-secondary': '#ffefeb',
        'surface-container-highest': '#D9EEFF',
        'error-container': '#f95630',
        'error-dim': '#b92902',
        background: '#F0F8FF',
        'surface-variant': '#D9EEFF',
        'on-tertiary': '#fff0e2',
        'tertiary-dim': '#6f4700',
        'on-secondary-container': '#802b0d',
        'primary-fixed': '#87CEEB',
        'surface-bright': '#F0F8FF',
        'on-error-container': '#520c00',
        'surface-tint': '#1A365D',
        'on-background': '#1A365D',
        'inverse-surface': '#0F2540',
        'on-secondary-fixed': '#651900',
        primary: '#1A365D',
        'inverse-primary': '#87CEEB',
      },
      borderRadius: {
        DEFAULT: '1rem',
        lg: '2rem',
        xl: '3rem',
        full: '9999px',
      },
      fontFamily: {
        tajawal: ['Tajawal', 'sans-serif'],
        almarai: ['Almarai', 'sans-serif'],
      },
    },
  },
  plugins: [require('@tailwindcss/forms'), require('@tailwindcss/container-queries')],
};
